# rules_objects.py — 物品交互类动作规则
"""使用/操作场景物品的动作——日常起居、电子娱乐、运动健身、饮食烹饪、户外活动。

这是最大的规则集。target_kind 全部为 "object"，action_type 全部为 "push"（通用执行原语）。
规则按域分节，每节有注释说明。
"""
from .rule_schema import CustomActionRule

OBJECT_RULES: tuple = (
    # ═══════════════════════════════════════════════════════════════════
    # 电子娱乐 (TV / 音响 / 电脑 / 卡拉OK / DJ)
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="watch_tv",
        label="📺 看电视",
        action_type="push",
        target_kind="object",
        hints=("TV_WatchRandomChannel", "tv_WatchCurrentChannelAutonomously"),
        verb="{actor} 看电视",
        target_match=("television", "电视", "tv_wall", "tv_flat", "tv_standing"),
        verified=True,
        note="TV_WatchRandomChannel(126983)→tv_WatchCurrentChannelAutonomously(34347)；2026-07-21 移除GenericOnOff_TurnOn（决策#13：TV不用此state）+ 收紧target_match防误匹配VideoGameConsole_TV",
    ),
    CustomActionRule(
        rule_id="turn_on_stereo",
        label="🔊 开音响",
        action_type="push",
        target_kind="object",
        hints=("stereo_TurnOnAndListen",),
        verb="{actor} 打开音响开始听音乐",
        target_match=("stereo", "speaker", "音响", "音箱", "djbooth"),
        target_exclude=("toilet", "马桶", "talking"),
        verified=True,
        min_age="Teen",
        object_state_forbidden=("broken", "burn"),
        note="stereo_TurnOnAndListen(14329) EA super=Y user=Y；与dance_stereo拆分为两个独立rule——跨轮：先开音响，下轮再跳；2026-07-22 +target_exclude防音乐马桶",
    ),
    CustomActionRule(
        rule_id="dance_stereo",
        label="💃 跟着音乐跳舞",
        action_type="push",
        target_kind="object",
        hints=("stereo_TurnOnAndListen", "stereo_Dance", "DJBooth_stereo_Dance",
               "stereo_Dance_WallSpeaker"),
        verb="{actor} 跟着音乐跳舞",
        target_match=("stereo", "speaker", "音响", "音箱", "djbooth"),
        target_exclude=("toilet", "马桶", "talking"),
        verified=True,
        min_age="Teen",
        object_state_forbidden=("broken", "burn"),
        note="stereo_TurnOnAndListen→stereo_Dance；2026-07-25 实测通过（真鳕+管家均TurnOnAndListen入队成功guaranteed）",
    ),
    CustomActionRule(
        rule_id="listen_music",
        label="🎵 听音乐",
        action_type="push",
        target_kind="object",
        hints=("stereo_listen", "stereo_TurnOnAndListen"),
        verb="{actor} 听音乐",
        target_match=("stereo", "音响", "音箱", "speaker"),
        target_exclude=("toilet", "马桶", "talking"),
        verified=True,
        min_age="Teen",
        note="stereo_listen(227249) EA super=Y user=Y→TurnOnAndListen(14329)；精确匹配优先→不再被子串劫持到ListenDeeply",
    ),
    CustomActionRule(
        rule_id="sing_karaoke",
        label="🎤 唱卡拉OK",
        action_type="push",
        target_kind="object",
        hints=("karaokeMachine_Autonomous_SongSelector_Solo",
               "karaokeMachine_Autonomous_SongSelector_Duet"),
        verb="{actor} 唱卡拉OK",
        target_match=("karaoke", "卡拉", "卡拉OK", "ktv"),
        verified=False,
        note="karaokeMachine_Autonomous_SongSelector_Solo(155149)→Duet(155150)；EA super=Y auto=Y user=N（push_super_affordance 可推；待实测）；CHILD+",
    ),
    CustomActionRule(
        rule_id="dj_practice",
        label="🎧 DJ打碟",
        action_type="push",
        target_kind="object",
        hints=("DJBooth_PlayMusic_genre_00_Practice_level01",),
        verb="{actor} 练习打碟",
        target_match=("djbooth", "dj", "打碟", "混音"),
        verified=True,
        note="DJBooth_PlayMusic_genre_00_Practice_level01(127738); EA super=Y auto=Y TEEN+; 2026-07-22 升verified——无DJ台时自然不匹配",
    ),
    CustomActionRule(
        rule_id="dance_djbooth",
        label="🕺 DJ台跳舞",
        action_type="push",
        target_kind="object",
        hints=("DJBooth_Dance",),
        verb="{actor} 在DJ台前跳舞",
        target_match=("djbooth", "dj", "dj台"),
        verified=False,
        min_age="Child",
        note="DJBooth_Dance(122399) EA super=Y auto=Y user=Y CHILD+；与stereo_Dance不同——这个是DJ台专属",
    ),
    CustomActionRule(
        rule_id="dance_floor",
        label="🪩 舞池跳舞",
        action_type="push",
        target_kind="object",
        hints=("DJBooth_Dance", "stereo_Dance"),
        verb="{actor} 在舞池跳舞",
        target_match=("dancefloor", "dance floor", "dance", "舞池", "舞"),
        target_exclude=("djbooth", "dj", "stereo", "音响"),
        verified=False,
        min_age="Child",
        note="DJBooth_Dance(122399)→stereo_Dance(14315)；舞池物品（DanceFloor模块）有独立dance affordance；待实测",
    ),
    # ── 电脑 ──
    CustomActionRule(
        rule_id="play_computer_game",
        label="🎮 玩电脑游戏",
        action_type="push",
        target_kind="object",
        hints=("computer_PlayGame_SimScuffle_E-Sports", "computer_VideoGaming_WatchStreams"),
        verb="{actor} 在电脑上玩游戏",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_PlayGame_SimScuffle_E-Sports(226202)+VideoGaming_WatchStreams(32052), EA super=Y auto=Y 全年龄",
    ),
    CustomActionRule(
        rule_id="browse_web",
        label="🌐 上网冲浪",
        action_type="push",
        target_kind="object",
        hints=("computer_Browse_Art", "computer_BlogLoveManifestations"),
        verb="{actor} 在电脑上网冲浪",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_Browse_Art(40074) EA super=Y auto=N user=Y 全年龄→BlogLoveManifestations(362091) auto=Y兜底；2026-07-22 实测通过（斑）",
    ),
    CustomActionRule(
        rule_id="practice_writing",
        label="✍️ 练习写作",
        action_type="push",
        target_kind="object",
        hints=("computer_PracticeWritingSkill",),
        verb="{actor} 在电脑上练习写作",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_PracticeWritingSkill(33877) EA super=Y auto=Y user=Y TEEN+；2026-07-22 实测通过（扉间）",
    ),
    CustomActionRule(
        rule_id="computer_social",
        label="📱 刷社交媒体",
        action_type="push",
        target_kind="object",
        hints=("computer_Social_Media_OpenSocialMedia",
               "computer_SocialNetwork_SocialMediaCareer_InternetPersonality_BroadcastStatus"),
        verb="{actor} 在电脑刷社交媒体",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_Social_Media_OpenSocialMedia(285076) EA super=Y auto=Y user=Y→BroadcastStatus(136798)；2026-07-22 实测通过（扉间）",
    ),
    CustomActionRule(
        rule_id="computer_programming",
        label="💻 编程",
        action_type="push",
        target_kind="object",
        hints=("computer_Programming_Practice", "computer_Programming_MakeGame",
               "computer_Programming_MakeApp"),
        verb="{actor} 在电脑上编程",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_Programming_Practice(31232)→MakeGame(36400)→MakeApp(33283); EA super=Y auto=Y user=Y TEEN+；2026-07-22 实测通过（扉间）",
    ),
    CustomActionRule(
        rule_id="computer_stream",
        label="📺 看游戏直播",
        action_type="push",
        target_kind="object",
        hints=("computer_StreamLetsPlay_SimsForever",
               "computer_VideoGaming_WatchStreams"),
        verb="{actor} 在电脑上看游戏直播",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=True,
        note="computer_StreamLetsPlay_SimsForever(136807)被拒→WatchStreams(32052)兜底成功；2026-07-22 实测通过（扉间）",
    ),
    CustomActionRule(
        rule_id="computer_hacking",
        label="🕵️ 黑客行动",
        action_type="push",
        target_kind="object",
        hints=("computer_HackMainframe", "computer_EV008_Hacking", "Computer_Programming_Hacking_SuperComputer"),
        verb="{actor} 在电脑上黑入主机",
        target_match=("computer", "电脑", "laptop", "笔记本"),
        verified=False,
        note="❌ 永久废弃——computer_HackMainframe(33955)需Criminal职业生涯，非通用动作；2026-07-22 实测确认 0/1 全拒；此规则保留仅作记录，verified 永不为 True",
    ),
    CustomActionRule(
        rule_id="tv_workout",
        label="📺 跟着电视运动",
        action_type="push",
        target_kind="object",
        hints=("TV_WatchRandomChannel", "tv_Watch_WorkOut_Dance",
               "tv_Watch_WorkOut_PowerSculpting"),
        verb="{actor} 跟着电视做运动",
        target_match=("television", "电视", "tv_wall", "tv_flat", "tv_standing"),
        verified=False,
        note="tv_Watch_WorkOut_Dance(164366)→PowerSculpting(164360); 2026-07-24 +TV_WatchRandomChannel首条——电视关→先开机跨轮再运动",
    ),
    CustomActionRule(
        rule_id="phone_play_games",
        label="📱 手机玩游戏",
        action_type="push",
        target_kind="self",
        hints=("phone_PlayGames_AutonomousOnly", "phone_PlayGames"),
        verb="{actor} 在手机上玩游戏",
        target_match=(),
        verified=False,
        note="phone_PlayGames_AutonomousOnly(99408) EA super=Y auto=N user=N（自主版，实测游戏盲选到此）；phone_PlayGames(13793) EA super=Y auto=N user=Y 兜底；2026-07-26 实测盲选命中AutonomousOnly，改为首选",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 运动健身
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="workout",
        label="🏋️ 健身",
        action_type="push",
        target_kind="object",
        hints=("WorkoutMachine_Workout", "WorkoutMachine_Workout_EpicWorkout",
               "WorkoutMachine_Workout_PushTheLimits"),
        verb="{actor} 在健身器材上锻炼",
        target_match=("workout", "weight", "健身", "杠铃", "哑铃", "器械"),
        verified=True,
        note="WorkoutMachine_Workout(14625)->EpicWorkout(26314)->PushTheLimits(98279), EA super=Y auto=Y",
    ),
    CustomActionRule(
        rule_id="treadmill_run",
        label="🏃 跑步机",
        action_type="push",
        target_kind="object",
        hints=("treadmill_Workout", "treadmill_Workout_Endurance",
               "treadmill_Workout_HillChallenge", "treadmill_Workout_NoSweat"),
        verb="{actor} 在跑步机上跑步",
        target_match=("treadmill", "跑步机"),
        verified=True,
        min_age="Teen",
        note="treadmill_Workout(14484)→Endurance(26325)→HillChallenge(26327)→NoSweat(26326)；EA super=Y auto=Y TEEN+；实测通过",
    ),
    CustomActionRule(
        rule_id="do_yoga",
        label="🧘 瑜伽",
        action_type="push",
        target_kind="object",
        hints=("si_Yoga_Routine_EnergyCentering", "si_Yoga_Routine_MindConcentrating",
               "si_Yoga_Routine_BrainBoosting", "si_Yoga_Routine_ChildFriendly"),
        verb="{actor} 做瑜伽",
        target_match=("yoga", "mat", "瑜伽", "瑜珈", "yogamat"),
        verified=True,
        note="si_Yoga_Routine_EnergyCentering(117407)→MindConcentrating(117409)→BrainBoosting(117408)；EA super=Y auto=Y TEEN+；实测通过（斑/真鳕/柱间）",
    ),
    CustomActionRule(
        rule_id="shoot_basketball",
        label="🏀 投篮",
        action_type="push",
        target_kind="object",
        hints=("basketball_TakeShots_Any", "basketball_TakeShots_Close",
               "basketball_TakeShots_2Point", "basketball_TakeShots_3Point"),
        verb="{actor} 打篮球投篮",
        target_match=("basketball", "hoop", "篮球", "篮筐"),
        verified=True,
        note="basketball_TakeShots_Any(146037)→Close(146013)→2Point(146015)→3Point(146016)；EA super=Y auto=Y CHILD+；实测通过（柱间）",
    ),
    CustomActionRule(
        rule_id="punching_bag",
        label="🥊 打拳击",
        action_type="push",
        target_kind="object",
        hints=("punchingBag_Box",),
        verb="{actor} 打拳击袋",
        target_match=("punching", "boxing", "拳击", "沙袋"),
        verified=True,
        note="punchingBag_Box EA super=Y auto=Y ADULT+；索引查证",
    ),
    CustomActionRule(
        rule_id="bowling",
        label="🎳 打保龄球",
        action_type="push",
        target_kind="object",
        hints=("bowlingLane_PlayGame",),
        verb="{actor} 打保龄球",
        target_match=("bowling", "保龄", "bowlinglane"),
        verified=True,
        note="bowlingLane_PlayGame EA super=Y auto=Y 全年龄；索引查证",
    ),
    CustomActionRule(
        rule_id="ice_skate",
        label="⛸ 溜冰",
        action_type="push",
        target_kind="object",
        hints=("waypoint_SkatingRink_SkateAround_HighSkill", "waypoint_SkatingRink_SkateAround_LowSkill"),
        verb="{actor} 溜冰",
        target_match=("skating", "skate", "溜冰", "滑冰", "rink"),
        verified=True,
        note="SkateAround_HighSkill→LowSkill兜底成功；EA super=Y auto=Y 全年龄；实测通过",
    ),
    CustomActionRule(
        rule_id="juggle_soccer",
        label="⚽ 颠球",
        action_type="push",
        target_kind="object",
        hints=("SI_SoccerBall_Juggle_Solo",),
        verb="{actor} 颠足球",
        target_match=("soccer", "football", "足球", "soccerball"),
        verified=True,
        note="SI_SoccerBall_Juggle_Solo(224308) EA super=Y auto=Y CHILD+；索引查证",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 音乐艺术
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="play_guitar",
        label="🎸 弹吉他",
        action_type="push",
        target_kind="object",
        hints=("guitar_Play_Song", "guitar_Play_Song_Inventory"),
        verb="{actor} 弹吉他",
        target_match=("guitar", "吉他"),
        verified=True,
        min_age="Teen",
        note="guitar_Play_Song EA super=Y auto=Y ADULT+；2026-07-20 实测通过",
    ),
    CustomActionRule(
        rule_id="play_piano",
        label="🎹 弹钢琴",
        action_type="push",
        target_kind="object",
        hints=("piano_Play_Song",),
        verb="{actor} 弹钢琴",
        target_match=("piano", "钢琴", "keyboard", "电子琴"),
        verified=True,
        note="piano_Play_Song(13808) EA super=Y auto=Y 全年龄",
    ),
    CustomActionRule(
        rule_id="play_violin",
        label="🎻 拉小提琴",
        action_type="push",
        target_kind="object",
        hints=("violin_Practice",),
        verb="{actor} 练习小提琴",
        target_match=("violin", "小提琴", "Violin"),
        verified=True,
        note="violin_Practice(14519) EA super=Y auto=Y ADULT+；索引查证",
    ),
    CustomActionRule(
        rule_id="paint_easel",
        label="🎨 画画",
        action_type="push",
        target_kind="object",
        hints=("canvas_scrapPainting", "easel_PracticePainting"),
        verb="{actor} 在画架上画画",
        target_match=("easel", "画架", "painteasel"),
        target_exclude=("canvas", "画布"),
        verified=False,
        note="canvas_scrapPainting(23740)→easel_PracticePainting(40778)。跨轮：有画→先舍弃画作(空slot)→下轮画",
    ),
    CustomActionRule(
        rule_id="arrange_flowers",
        label="💐 插花",
        action_type="push",
        target_kind="object",
        hints=("Marquillo:SBO_SI_flowerArrangement_StartCraftingAutonomously_NPC",
               "crafting_resume_flowerarrangement"),
        verb="{actor} 插花",
        target_match=("flowerarrang", "插花"),
        target_exclude=("flower", "花", "plant", "植物", "floral", "arrangement"),
        verified=False,
        note="2026-07-24 收紧target_match去floral/arrangement防误匹配装饰物+target_exclude防误匹配园艺植物；Marquillo:SBO MOD StartCrafting(super=Y,auto=Y,user=N)",
    ),
    CustomActionRule(
        rule_id="perform_comedy",
        label="🎤 表演喜剧",
        action_type="push",
        target_kind="object",
        hints=("microphone_StartComedyRoutine", "microphone_PickComedyRoutine"),
        verb="{actor} 在舞台上表演喜剧",
        target_match=("microphone", "mic", "麦克风", "话筒"),
        target_exclude=("karaoke", "卡拉"),
        verified=True,
        min_age="Teen",
        note="microphone_StartComedyRoutine(30948)→PickComedyRoutine(30947); 2026-07-24 修复：performanceSpace_PerformComedy_Start不存在",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 饮食
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="fridge_snack",
        label="🍽 从冰箱拿吃的",
        action_type="push",
        target_kind="object",
        hints=("fridge_GrabDrinkAutonomously",),
        verb="{actor} 从冰箱拿吃的",
        target_match=("fridge", "冰箱"),
        verified=True,
        min_age="Teen",
        note="2026-07-25 探针审计：fridge_GrabSnack 在 EA 原版不存在，实测一直靠 GrabDrinkAutonomously 兜底成功",
    ),
    CustomActionRule(
        rule_id="fridge_cook_meal",
        label="🍳 做全家餐",
        action_type="push",
        target_kind="object",
        hints=("fridge_CookAutonomously",),
        verb="{actor} 从冰箱取食材做饭",
        target_match=("fridge", "冰箱"),
        verified=True,
        min_age="Teen",
        note="fridge_CookAutonomously(13388) EA super=Y auto=Y——自主烹饪不弹食谱；2026-07-25 真鳕实测旧版 fridge_Cook 呆站→换自主变体",
    ),
    CustomActionRule(
        rule_id="counter_prepare",
        label="🔪 备菜切菜",
        action_type="push",
        target_kind="object",
        hints=("counter_MakeFood_Staging_Basic",),
        verb="{actor} 在台面上备菜",
        target_match=("counter", "台面", "橱柜", "厨房台"),
        target_exclude=("bathroom", "浴室", "sink", "水槽"),
        verified=True,
        min_age="Teen",
        note="counter_MakeFood_Staging_Basic(13277) EA super=Y；烹饪多阶段：冰箱取食材→台面备菜→炉灶做菜",
    ),
    CustomActionRule(
        rule_id="stove_cook",
        label="🔥 炉灶做菜",
        action_type="push",
        target_kind="object",
        hints=("generic_cook",),
        verb="{actor} 用炉灶做菜",
        target_match=("stove", "炉灶", "cooktop", "炉", "灶"),
        verified=True,
        min_age="Teen",
        note="generic_cook(13434) EA super=Y；烹饪多阶段需跨轮或期待 AI 选 fridge_cook_meal 一步完成",
    ),
    CustomActionRule(
        rule_id="grill_cook",
        label="🍖 烧烤烹饪",
        action_type="push",
        target_kind="object",
        hints=("grill_StartCraftingAutonomously", "generic_grill"),
        verb="{actor} 在烧烤架上做菜",
        target_match=("bbq", "pitbbq", "grill", "烧烤"),
        verified=True,
        min_age="Teen",
        note="grill_StartCraftingAutonomously(38875) EA super=Y auto=Y→generic_grill(35025)；烧烤自带完整流水线；2026-07-25 真鳕实测通过",
    ),
    CustomActionRule(
        rule_id="bbq_grab_food",
        label="🍖 烧烤拿食物",
        action_type="push",
        target_kind="object",
        hints=("pitBBQ_GrabFood", "pitBBQ_PickUp_ReplaceConsume"),
        verb="{actor} 从烧烤架拿食物",
        target_match=("bbq", "pitbbq", "烧烤", "grill"),
        verified=True,
        min_age="Child",
        note="pitBBQ_GrabFood(204980)→PickUp_ReplaceConsume(211723)；EA super=Y auto=Y user=Y CHILD+",
    ),
    CustomActionRule(
        rule_id="grab_coffee",
        label="☕ 喝咖啡",
        action_type="push",
        target_kind="object",
        hints=("coffeeMaker_StartCrafting_Pot", "coffeeMaker_Grab"),
        verb="{actor} 拿杯咖啡喝",
        target_match=("coffeemaker", "espresso", "咖啡机", "咖啡壶"),
        target_exclude=("table", "茶几"),
        verified=True,
        min_age="Teen",
        note="coffeeMaker_StartCrafting_Pot(77662)→coffeeMaker_Grab(13165)；跨轮：空壶先煮，下轮再拿；2026-07-26 实测入队成功→标verified",
    ),
    CustomActionRule(
        rule_id="grab_tea",
        label="🍵 喝茶",
        action_type="push",
        target_kind="object",
        hints=("teaMaker_Grab", "brew_WaitFor_Pot_Tea", "brew_WaitFor_Single_Tea"),
        verb="{actor} 拿杯茶喝",
        target_match=("tea", "茶", "teamaker", "kettle", "热水壶"),
        verified=True,
        min_age="Teen",
        note="teaMaker_Grab(76985)→brew_WaitFor_Pot(77081)→brew_Single(77082)；EA super=Y auto=Y user=Y TEEN+",
    ),
    CustomActionRule(
        rule_id="drink_bubble_tea",
        label="🧋 喝奶茶",
        action_type="push",
        target_kind="object",
        hints=("consume_Drink_NonBar_BubbleTea", "consume_Drink_Nonbar_BubbleTea_Straw"),
        verb="{actor} 喝奶茶",
        target_match=("bubbletea", "bubble_tea", "bubble tea", "奶茶"),
        verified=True,
        min_age="Teen",
        note="consume_Drink_NonBar_BubbleTea(281058)→Straw(281151); EA super=Y auto=Y user=Y TEEN+；2026-07-22 斑+真鳕实测通过",
    ),
    CustomActionRule(
        rule_id="tend_bar",
        label="🍹 调酒",
        action_type="push",
        target_kind="object",
        hints=("bar_Tendbar", "bar_PracticeDrinkMaking", "globeBar_MakeDrink_Autonomous"),
        verb="{actor} 在吧台调酒",
        target_match=("bar", "吧台", "globe", "pub"),
        verified=True,
        note="bar_Tendbar(13063,user=Y)→bar_PracticeDrinkMaking(108956,user=N)→globeBar_MakeDrink(149422,user=N)；EA super=Y auto=Y TEEN+；实测通过（柱间；斑缺trait被拒）",
    ),
    CustomActionRule(
        rule_id="bbq_hangout",
        label="🍖 烧烤架旁闲逛",
        action_type="push",
        target_kind="object",
        hints=("pitBBQ_HangOut", "pitBBQ_CloseCover"),
        verb="{actor} 在烧烤架旁闲逛",
        target_match=("bbq", "pitbbq", "烧烤", "grill"),
        verified=True,
        min_age="Child",
        note="pitBBQ_HangOut(209623)→CloseCover(211912)；EA super=Y auto=Y user=Y CHILD+",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 睡眠休息
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="bed_sleep",
        label="🛏 上床睡觉",
        action_type="push",
        target_kind="object",
        hints=("bed_Autonomous_DoubleBed_Sleep", "bed_Autonomous_SingleBed_Sleep",
               "bed_Sleep_SleepingBag"),
        verb="{actor} 上床睡觉",
        target_match=("bed", "床", "bunk", "murphy"),
        target_exclude=("sofa", "couch", "沙发", "chair", "躺椅", "toddler", "infant", "crib"),
        verified=True,
        min_age="Child",
        note="bed_Autonomous_DoubleBed_Sleep(100082)→SingleBed(100083)→SleepingBag(314759)",
    ),
    CustomActionRule(
        rule_id="bed_relax",
        label="🛏 床上放松",
        action_type="push",
        target_kind="object",
        hints=("bed_relax_doubleBed",),
        verb="{actor} 在床上放松休息",
        target_match=("bed", "床"),
        target_exclude=("sofa", "couch", "沙发", "chair", "toddler", "infant", "crib"),
        verified=True,
        min_age="Child",
        note="bed_relax_doubleBed(268282) EA super=Y auto=Y user=Y CHILD+；与bed_sleep互补——这个是休息不睡觉",
    ),
    CustomActionRule(
        rule_id="sofa_nap",
        label="😴 沙发小憩",
        action_type="push",
        target_kind="object",
        hints=("sofa_Nap", "generic_SofaNap", "sectional_Sofa_Chaise_Nap"),
        verb="{actor} 在沙发上小憩",
        target_match=("sofa", "couch", "loveseat", "沙发", "躺椅"),
        verified=True,
        min_age="Teen",
        note="sofa_Nap(14305) EA; +generic_SofaNap(28880)+sectional(260139) 兜底快照匹配；实测通过",
    ),
    CustomActionRule(
        rule_id="cry_under_covers",
        label="😢 蒙头大哭",
        action_type="push",
        target_kind="object",
        hints=("Bed_Undercovers_Cry",),
        verb="{actor} 蒙在被子里大哭",
        target_match=("bed", "床"),
        target_exclude=("sofa", "couch", "沙发", "chair", "toddler", "infant", "crib"),
        verified=False,
        note="Bed_Undercovers_Cry(33975) EA super=Y auto=Y user=Y 全年龄；情绪化动作——需要Sad/VerySad情绪buff",
    ),
    CustomActionRule(
        rule_id="hide_under_covers",
        label="🫣 躲进被窝",
        action_type="push",
        target_kind="object",
        hints=("Bed_Undercovers_Hide",),
        verb="{actor} 躲进被窝里藏起来",
        target_match=("bed", "床"),
        target_exclude=("sofa", "couch", "沙发", "chair", "toddler", "infant", "crib"),
        verified=True,
        note="Bed_Undercovers_Hide(34080) EA super=Y auto=Y user=Y TEEN+；2026-07-24 柱间实测通过",
    ),
    CustomActionRule(
        rule_id="sofa_sit",
        label="🪑 坐下",
        action_type="push",
        target_kind="object",
        hints=("seating_Sit",),
        verb="{actor} 坐下休息",
        target_match=("sofa", "couch", "loveseat", "chair", "沙发", "椅子", "躺椅",
                      "sit", "seat", "stool", "bench"),
        verified=True,
        min_age="Child",
        note="seating_Sit(31564) EA super=Y auto=Y user=Y tgt=OBJECT——queue_diff实证游戏在推；可与sofa_Nap互补",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 卫生
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="take_shower",
        label="🚿 淋浴",
        action_type="push",
        target_kind="object",
        hints=("shower_TakeShower", "shower_TakeShower_Energized"),
        verb="{actor} 去淋浴",
        target_match=("shower", "淋浴", "showerstall"),
        verified=True,
        min_age="Child",
        note="shower_TakeShower(13950)→Energized(23839)；EA super=Y auto=Y CHILD+；实测通过",
    ),
    CustomActionRule(
        rule_id="take_bath",
        label="🛁 泡澡",
        action_type="push",
        target_kind="object",
        hints=("bathtub_TakeBath", "bathtub_TakeBath_Mermaid"),
        verb="{actor} 泡澡",
        target_match=("bathtub", "浴缸", "澡盆", "bath"),
        verified=True,
        min_age="Child",
        note="bathtub_TakeBath(13084)→Mermaid(213938)；EA super=Y auto=Y CHILD+；实测通过",
    ),
    CustomActionRule(
        rule_id="brush_teeth",
        label="🪥 刷牙",
        action_type="push",
        target_kind="object",
        hints=("sink_BrushTeeth",),
        verb="{actor} 刷牙",
        target_match=("sink", "水槽", "洗手池", "洗手盆"),
        verified=True,
        note="sink_BrushTeeth(14238) EA super=Y auto=Y user=Y CHILD+；2026-07-22 实测通过（扉间）",
    ),
    CustomActionRule(
        rule_id="wash_hands",
        label="🧼 洗手",
        action_type="push",
        target_kind="object",
        hints=("sink_washHands", "sink_washHands_OffTheGrid"),
        verb="{actor} 洗手",
        target_match=("sink", "水槽", "洗手池", "洗碗槽", "basin"),
        target_exclude=("dishwasher", "洗碗机"),
        verified=True,
        min_age="Child",
        note="sink_washHands(14241)→OffTheGrid(212088)；EA super=Y auto=Y user=Y CHILD+",
    ),
    CustomActionRule(
        rule_id="use_toilet",
        label="🚽 上厕所",
        action_type="push",
        target_kind="object",
        hints=("generic_ToiletSit", "generic_ToiletStand", "generic_ToiletSit_Stall"),
        verb="{actor} 上厕所",
        target_match=("toilet", "马桶", "厕所", "urinal", "小便池"),
        target_exclude=("talking",),
        verified=True,
        min_age="Child",
        note="generic_ToiletSit(13443)→Stand→Stall(213986)；EA super=Y user=N但push实测可用",
    ),
    CustomActionRule(
        rule_id="chat_talking_toilet",
        label="🚽💬 和语音马桶聊天",
        action_type="push",
        target_kind="object",
        hints=("TalkingToilet_Social_friendly_Chitchat_start",),
        verb="{actor} 和语音马桶聊天",
        target_match=("talkingtoilet", "talking toilet", "toilet talking", "语音马桶", "音乐马桶", "hitech"),
        verified=True,
        min_age="Child",
        note="TalkingToilet_Social_friendly_Chitchat_start(134202) EA super=Y user=Y CHILD+",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 户外娱乐
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="pool_swim",
        label="🏊 游泳",
        action_type="push",
        target_kind="object",
        hints=("Pool_Get_In",),
        verb="{actor} 跳进泳池游泳",
        target_match=("swimmingpool", "swimming_pool", "泳池"),
        target_exclude=("seat", "emitter", "ladder", "kiddie", "儿童", "inflatable"),
        verified=True,
        min_age="Child",
        note="Pool_Get_In(103569) EA super=Y auto=Y user=N；2026-07-25 审计收紧target_match——'pool'子串命中187个泳池座位+112个Emitter",
    ),
    CustomActionRule(
        rule_id="kiddie_pool_lounge",
        label="🦆 戏水池泡水",
        action_type="push",
        target_kind="object",
        hints=("KiddiePool_Lounge",),
        verb="{actor} 在儿童戏水池里泡着",
        target_match=("kiddie", "inflatable", "戏水", "儿童泳池"),
        verified=False,
        note="KiddiePool_Lounge(188816) EA super=Y auto=Y user=Y 全年龄；待实测",
    ),
    CustomActionRule(
        rule_id="diving_board",
        label="🤸 跳水",
        action_type="push",
        target_kind="object",
        hints=("divingBoard_Start_Basic", "divingBoard_Start_Cannonball",
               "divingBoard_Start_SwanDive", "divingBoard_Start_Backflip"),
        verb="{actor} 从跳板跳水",
        target_match=("divingboard", "diving board", "diving", "跳板", "跳水"),
        verified=False,
        min_age="Child",
        note="divingBoard_Start_Basic(453780)→Cannonball(453773)→SwanDive(453774)→Backflip(453772)；EA super=Y auto=Y user=Y CHILD+；待实测",
    ),
    CustomActionRule(
        rule_id="ocean_dive",
        label="🤿 自由潜水",
        action_type="push",
        target_kind="object",
        hints=("OceanDiving_Freediving", "OceanDiving_ClothesSpin_Freediving"),
        verb="{actor} 在海里自由潜水",
        target_match=("oceandiving", "ocean", "dive", "buoy", "浮标"),
        verified=False,
        min_age="Teen",
        note="OceanDiving_Freediving(204909)→ClothesSpin(207359)；EA super=Y auto=Y user=Y TEEN+；仅海岛/沿海地段可用；待实测",
    ),
    CustomActionRule(
        rule_id="swing_set",
        label="🪑 荡秋千",
        action_type="push",
        target_kind="object",
        hints=("SwingSet_SoloSwing",),
        verb="{actor} 荡秋千",
        target_match=("swingset", "swing", "秋千"),
        target_exclude=("mood", "teen", "emotion"),
        verified=False,
        note="SwingSet_SoloSwing(186158) EA super=Y auto=Y user=Y 全年龄；待实测",
    ),
    CustomActionRule(
        rule_id="playground_slide",
        label="🛝 滑滑梯",
        action_type="push",
        target_kind="object",
        hints=("ModularPlayground_StraightSlide_SlideDown",
               "ModularPlayground_SpiralSlide_SlideDown"),
        verb="{actor} 滑滑梯",
        target_match=("slide", "滑梯", "playground"),
        target_exclude=("microscope", "guitar", "water", "ladder"),
        verified=True,
        note="StraightSlide_SlideDown(465355)→SpiralSlide(465351)；EA super=Y auto=Y user=Y 全年龄含toddler",
    ),
    CustomActionRule(
        rule_id="climbing_wall_playground",
        label="🧗 爬攀岩墙",
        action_type="push",
        target_kind="object",
        hints=("ModularPlayground_ClimbingWall_ClimbUp",),
        verb="{actor} 爬游乐场攀岩墙",
        target_match=("climbingwall", "climbing", "攀岩", "攀爬墙"),
        target_exclude=("route", "rock", "mountain"),
        verified=False,
        note="ClimbingWall_ClimbUp(465452) EA super=Y auto=Y user=Y 全年龄；待实测",
    ),
    CustomActionRule(
        rule_id="playground_tunnel",
        label="🚇 钻隧道",
        action_type="push",
        target_kind="object",
        hints=("ModularPlayground_TraverseTunnel",),
        verb="{actor} 在游乐场隧道里钻爬",
        target_match=("tunnel", "隧道", "playground"),
        verified=False,
        note="TraverseTunnel(464895) EA super=Y auto=Y user=Y 全年龄含toddler；待实测",
    ),
    CustomActionRule(
        rule_id="jungle_gym_spaceship",
        label="🚀 太空船攀爬架",
        action_type="push",
        target_kind="object",
        hints=("JungleGymRocketship_Spacewalk",),
        verb="{actor} 在太空船攀爬架上玩",
        target_match=("rocketship", "junglegym", "jungle gym", "攀爬架", "太空船"),
        verified=False,
        min_age="Child",
        note="JungleGymRocketship_Spacewalk(73950) EA super=Y auto=Y user=Y CHILD；2026-07-24 柱间(成人)实测被拒→加min_age硬过滤",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 休闲桌游
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="play_chess",
        label="♟ 下国际象棋",
        action_type="push",
        target_kind="object",
        hints=("Chess_Social",),
        verb="{actor} 下棋",
        target_match=("chess", "棋", "国际象棋"),
        verified=True,
        note="Chess_Social(13155) EA super=Y auto=Y 全年龄；实测通过",
    ),
    CustomActionRule(
        rule_id="play_darts",
        label="🎯 玩飞镖",
        action_type="push",
        target_kind="object",
        hints=("si_Dartboard_StartPlaying", "si_Dartboard_ThrowDarts"),
        verb="{actor} 玩飞镖",
        target_match=("dart", "飞镖"),
        verified=False,
        min_age="Child",
        note="si_Dartboard_StartPlaying(128280) EA super=Y auto=Y user=Y 🥇 +ThrowDarts(127473) 🥈；queue_diff实证推入成功",
    ),
    CustomActionRule(
        rule_id="dollhouse_play",
        label="🏠 玩娃娃屋",
        action_type="push",
        target_kind="object",
        hints=("DollHouse_Play",),
        verb="{actor} 玩娃娃屋",
        target_match=("dollhouse", "doll house", "娃娃屋", "玩具屋"),
        verified=False,
        note="DollHouse_Play(13337) EA super=Y auto=Y user=Y 全年龄含toddler；待实测",
    ),
    CustomActionRule(
        rule_id="dont_wake_llama",
        label="🦙 玩别吵醒羊驼",
        action_type="push",
        target_kind="object",
        hints=("DontWakeLlama_PlayWith", "GameTable_ChangeGame_DontWakeLlama_Yeti"),
        verb="{actor} 玩「别吵醒羊驼」桌游",
        target_match=("dontwakellama", "llama", "羊驼", "gametable", "game table", "游戏桌"),
        verified=False,
        note="DontWakeLlama_PlayWith(127355)→GameTable_ChangeGame(295115)；EA super=Y auto=Y user=Y；待实测",
    ),
    CustomActionRule(
        rule_id="arcade_watch",
        label="🕹 看街机游戏",
        action_type="push",
        target_kind="object",
        hints=("ArcadeMachine_WatchArcadeGame",),
        verb="{actor} 看街机游戏画面",
        target_match=("arcade", "街机", "arcademachine"),
        verified=False,
        note="ArcadeMachine_WatchArcadeGame(127417) EA super=Y auto=Y user=Y 全年龄；待实测",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 养生SPA
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="meditate",
        label="🧘 冥想",
        action_type="push",
        target_kind="object",
        hints=("immediate_GuidedMeditation_Start_Public_Free",),
        verb="{actor} 坐下来冥想",
        target_match=("meditation", "stool", "冥想", "meditationstool"),
        verified=True,
        min_age="Child",
        note="immediate_GuidedMeditation_Start_Public_Free(272194) EA super=Y auto=N user=Y",
    ),
    CustomActionRule(
        rule_id="facial_mask",
        label="💆 敷面膜",
        action_type="push",
        target_kind="object",
        hints=("facialMask_PurchaseToApply_Start",),
        verb="{actor} 敷面膜保养",
        target_match=("facialmask", "facial", "面膜", "skincare", "spa"),
        target_exclude=("child",),
        verified=True,
        min_age="Teen",
        note="facialMask_PurchaseToApply_Start(273363) EA super=Y auto=Y user=Y TEEN+",
    ),
    CustomActionRule(
        rule_id="light_incense",
        label="🕯 点香薰",
        action_type="push",
        target_kind="object",
        hints=("incense_LightSage", "incense_LightSandalwood", "incense_LightCinnamon"),
        verb="{actor} 点燃香薰",
        target_match=("incense", "香薰", "熏香", "incenseholder"),
        verified=False,
        note="incense_LightSage(118483)→Sandalwood(118479)→Cinnamon(118482)；EA super=Y auto=N user=Y TEEN+；待实测",
    ),
    CustomActionRule(
        rule_id="massage_chair",
        label="💺 按摩椅放松",
        action_type="push",
        target_kind="object",
        hints=("massageChair_Tend",),
        verb="{actor} 享受按摩椅",
        target_match=("massagechair", "massage chair", "按摩椅"),
        verified=True,
        min_age="Teen",
        note="massageChair_Tend(272111) EA super=Y auto=N user=Y TEEN+",
    ),
    CustomActionRule(
        rule_id="use_bubble_blower",
        label="🍵 吹泡泡",
        action_type="push",
        target_kind="object",
        hints=("BubbleBlower_Use_SI", "si_BubbleBottle_blow_bubbles"),
        verb="{actor} 吹泡泡",
        target_match=("bubbleblower", "bubble_blower", "bubble_bottle", "blow_bubbles",
                      "泡泡机", "泡泡瓶", "hookah", "水烟"),
        verified=True,
        note="BubbleBlower_Use_SI(134002)→si_BubbleBottle_blow_bubbles(146905)；Blower=大水烟壶/Bottle=手持小瓶→两种都覆盖",
    ),

    # ═══════════════════════════════════════════════════════════════════
    # 其他（镜子/望远镜/日记/壁炉/热水浴/显微镜/户外/自然）
    # ═══════════════════════════════════════════════════════════════════
    CustomActionRule(
        rule_id="mirror_practice",
        label="🪞 对着镜子练习",
        action_type="push",
        target_kind="object",
        hints=("mirror_PracticeSpeech", "mirror_PracticeStory"),
        verb="{actor} 对着镜子练习演讲",
        target_match=("mirror", "镜子", "mirror"),
        verified=True,
        note="mirror_PracticeSpeech EA super=Y auto=Y 全年龄；实测通过",
    ),
    CustomActionRule(
        rule_id="mirror_gussy",
        label="🪞 照镜子整理",
        action_type="push",
        target_kind="object",
        hints=("mirror_GussyUp", "mirror_GussyUp_Vanity", "mirror_AdmireSelf"),
        verb="{actor} 照镜子整理仪容",
        target_match=("mirror", "镜子", "vanity", "梳妆"),
        verified=True,
        min_age="Teen",
        note="mirror_GussyUp(13621)→Vanity(145216)→AdmireSelf(13603)；EA super=Y user=Y；实测通过",
    ),
    CustomActionRule(
        rule_id="mirror_practice_dance",
        label="🪞💃 镜子前练舞",
        action_type="push",
        target_kind="object",
        hints=("mirrorFloor_PracticeDancing",),
        verb="{actor} 在镜子前练习跳舞",
        target_match=("mirrorfloor", "floor_mirror", "floor mirror", "full_length", "落地镜", "mirror_floor"),
        verified=False,
        min_age="Child",
        note="mirrorFloor_PracticeDancing(128199) EA super=Y auto=Y user=Y CHILD+；注意是落地镜(mirrorFloor)非壁挂镜",
    ),
    CustomActionRule(
        rule_id="telescope_stargaze",
        label="🔭 观星",
        action_type="push",
        target_kind="object",
        hints=("Telescope_StarGaze", "Telescope_ObserveSkies"),
        verb="{actor} 用望远镜观星",
        target_match=("telescope", "望远镜", "Telescope", "observatory"),
        verified=True,
        note="Telescope_StarGaze+ObserveSkies EA super=Y auto=Y 全年龄；实测通过（注意：仅夜20:30-06:00可用，白天会被拒）",
    ),
    CustomActionRule(
        rule_id="write_journal",
        label="📝 写日记",
        action_type="push",
        target_kind="object",
        hints=("book_Journal_Write",),
        verb="{actor} 写日记",
        target_match=("journal", "日记", "Journal"),
        verified=True,
        note="book_Journal_Write EA super=Y auto=Y 全年龄；索引查证",
    ),
    CustomActionRule(
        rule_id="read_book",
        label="📖 看书",
        action_type="push",
        target_kind="object",
        hints=("bookshelf_ReadRandom_Rallyable",),
        verb="{actor} 从书架拿书看",
        target_match=("bookshelf", "bookcase", "书架", "书柜"),
        verified=True,
        note="bookshelf_ReadRandom_Rallyable(127423) EA super=Y auto=Y 全年龄；实测通过",
    ),
    CustomActionRule(
        rule_id="fireplace_warm",
        label="🔥 烤火取暖",
        action_type="push",
        target_kind="object",
        hints=("Fireplace_Light", "Fireplace_WarmSelf"),
        verb="{actor} 在壁炉旁取暖",
        target_match=("fireplace", "壁炉", "Fireplace"),
        verified=True,
        note="Fireplace_Light(74767)→Fireplace_WarmSelf(74768)；2026-07-21 实测通过（壁炉灭→Fireplace_Light 自动点火→取暖；跨轮模式验证通过）",
    ),
    CustomActionRule(
        rule_id="roast_marshmallows",
        label="🔥 烤棉花糖",
        action_type="push",
        target_kind="object",
        hints=("campfire_AddLog", "campfire_startCrafting", "campfire_RoastMarshmallows"),
        verb="{actor} 在篝火旁烤棉花糖",
        target_match=("campfire",),
        verified=False,
        object_state_forbidden=("broken", "burn"),
        note="campfire_AddLog(102352)→startCrafting(105165)→RoastMarshmallows(105231)；同壁炉模式；只用英文type防中文误命中bonfire",
    ),
    CustomActionRule(
        rule_id="hottub_soak",
        label="♨️ 泡热水浴",
        action_type="push",
        target_kind="object",
        hints=("HotTub_Get_In",),
        verb="{actor} 泡热水浴",
        target_match=("hottub", "hot_tub", "hot tub", "按摩浴缸", "hottub"),
        verified=True,
        note="HotTub_Get_In(117259) EA super=Y auto=Y 全年龄；实测通过",
    ),
    CustomActionRule(
        rule_id="bee_keeping",
        label="🐝 采集蜂蜡",
        action_type="push",
        target_kind="object",
        hints=("BeeBox_GatherBeesWax",),
        verb="{actor} 从蜂箱采集蜂蜡",
        target_match=("beebox", "bee", "beehive", "蜂箱", "蜂巢", "蜜蜂"),
        verified=False,
        min_age="Teen",
        note="BeeBox_GatherBeesWax(237323) EA super=Y auto=Y user=Y TEEN+；乡村DLC；待实测",
    ),
    CustomActionRule(
        rule_id="insect_view",
        label="🦋 观察昆虫标本",
        action_type="push",
        target_kind="object",
        hints=("Collectible_Insect_View_generic",),
        verb="{actor} 观察昆虫标本",
        target_match=("insect", "昆虫", "标本", "butterfly", "beetle", "butterflycollection"),
        target_exclude=("incubator", "孵化"),
        verified=False,
        note="Collectible_Insect_View_generic(102963) EA super=Y auto=Y user=Y 全年龄；待实测",
    ),
    CustomActionRule(
        rule_id="costume_box",
        label="🎭 换装扮演",
        action_type="push",
        target_kind="object",
        hints=("costumeBox_WearCostume_Playful_Robot",),
        verb="{actor} 从换装箱里挑戏服穿",
        target_match=("costumebox", "costume", "戏服", "换装", "dressup"),
        verified=False,
        note="costumeBox_WearCostume_Playful_Robot(361489) EA super=Y auto=Y user=Y TEEN+；待实测",
    ),
)
