# rules_motive.py — 清洁/收集/维护类动作规则
"""自动触发的环境维护动作——看到脏乱就做，不走 AI 决策。

全部 auto_trigger=True：程序每轮扫描场景物品状态，匹配后按优先级（修理>清洁>收集）
分配角色执行。object_state_requires 确保只在物品确实需要处理时才触发。
"""
from .rule_schema import CustomActionRule

MOTIVE_RULES: tuple = (
    # ── 收集类（P1 优先级）──
    CustomActionRule(
        rule_id="collect_laundry",
        label="🧺 收脏衣服",
        action_type="push",
        target_kind="object",
        hints=("Collect_Laundry",),
        verb="收拾地上的脏衣服",
        target_match=("laundry", "clothingpile", "cloth", "clothes", "洗衣", "脏衣", "衣服"),
        target_exclude=("hamper", "basket", "dresser", "washer", "dryer", "machine",
                        "laundry_basket", "laundrybasket", "closet", "wardrobe", "hang_clothes"),
        verified=True,
        auto_trigger=True,
        object_state_requires=("laundry", "dirty", "filthy", "cloth"),
        note="collect_Laundry(175356) EA super=Y auto=Y user=Y TEEN+；2026-07-22 升verified；2026-07-28 补 object_state_requires + target_exclude",
    ),
    CustomActionRule(
        rule_id="collect_trash",
        label="🗑 收垃圾",
        action_type="push",
        target_kind="object",
        hints=("Collect_Trash",),
        verb="收拾垃圾",
        target_match=("trash", "垃圾", "rubbish", "garbage", "pile"),
        target_exclude=("trashcan", "trash_can", "trashchute", "garbagecan", "garbage_can",
                        "outdoor_trash", "diaper", "recycle"),
        verified=True,
        auto_trigger=True,
        object_state_requires=("trash", "garbage", "dirty"),
        note="Collect_Trash(13175) EA super=Y auto=Y user=Y 全年龄；2026-07-21 实测通过（扉间）；2026-07-28 补 object_state_requires + target_exclude",
    ),
    CustomActionRule(
        rule_id="collect_dish",
        label="🍽 收碗碟",
        action_type="push",
        target_kind="object",
        hints=("Collect_Dish", "Collect_Dish_After_Eating"),
        verb="收拾碗碟",
        target_match=("dish", "plate", "碗", "碟", "bowl"),
        target_exclude=("dishwasher", "petbowl", "pet_bowl", "pet_food"),
        verified=True,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy"),
        note="Collect_Dish(13169)→Collect_Dish_After_Eating(74918)；EA super=Y auto=Y user=Y 全年龄；2026-07-21 实测通过（扉间）；2026-07-28 补 object_state_requires + target_exclude",
    ),
    CustomActionRule(
        rule_id="load_dishwasher",
        label="🍽 装洗碗机",
        action_type="push",
        target_kind="object",
        hints=("dishwasher_LoadDishes",),
        verb="{actor} 把碗放进洗碗机",
        target_match=("dishwasher", "洗碗机", "洗碗"),
        verified=True,
        auto_trigger=True,
        min_age="teen",
        object_state_forbidden=("inuse",),
        note="observer 实证：dishwasher_LoadDishes 游戏自主体使用 6 次；2026-07-29 +forbidden inuse +min_age=teen——幼儿被拒（ADULT/ELDER only）",
    ),
    # ── 清洁类（P2 优先级）──
    CustomActionRule(
        rule_id="mop_puddle",
        label="💧 拖水坑",
        action_type="push",
        target_kind="object",
        hints=("Puddle_Mop", "Puddle_Mop_Large", "Puddle_Mop_Small",
               "Puddle_Mop_Energized", "Puddle_Mop_Energized_Large", "Puddle_Mop_Energized_Small"),
        verb="拖地",
        target_match=("puddle", "水坑", "水洼", "水渍"),
        verified=True,
        auto_trigger=True,
        object_state_requires=("puddle",),
        note="Puddle_Mop(13835)→Large(27285)→Small(27284) + Energized(13836)→L(27291)→S(27290)；EA 6变体全覆盖 super=Y auto=Y user=Y 全年龄；2026-07-21 +状态感知；2026-07-28 +Energized三变体——普通版禁Energized心情",
    ),
    CustomActionRule(
        rule_id="clean_counter",
        label="🧹 清洁台面",
        action_type="push",
        target_kind="object",
        hints=("counter_Clean",),
        verb="{actor} 擦拭台面，去掉污渍",
        target_match=("counter", "countertop", "island", "台面", "柜台"),
        target_exclude=("sink", "wash", "水槽", "洗手", "bar", "吧台"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy"),
        object_state_forbidden=("broken", "burn", "clog", "spoil"),
        note="counter_Clean(29829) super=Y auto=Y user=Y tgt=OBJECT；2026-07-25 首测：台面匹配到水槽→拒→落sink_washHands；+exclude水槽/吧台；2026-07-28 +requires dirty；2026-07-29 verified→False——SituationRunningTest门控，干净台面游戏拒推，AI不应选（自动层自有状态过滤）",
    ),
    CustomActionRule(
        rule_id="clean_desk",
        label="🧹 清洁书桌",
        action_type="push",
        target_kind="object",
        hints=("Desk_Clean",),
        verb="{actor} 整理书桌，清理灰尘",
        target_match=("desk", "书桌", "电脑桌", "办公桌", "写字台"),
        target_exclude=("front", "reception", "vanity", "computer", "电脑", "laptop"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy"),
        object_state_forbidden=("broken", "burn", "clog", "spoil"),
        note="Desk_Clean(100035) super=Y auto=Y user=Y；2026-07-25 实测desk误命中电脑(lockComputer)→+exclude防误匹；2026-07-28 +requires dirty",
    ),
    CustomActionRule(
        rule_id="clean_bar",
        label="🧹 清洁吧台",
        action_type="push",
        target_kind="object",
        hints=("bar_Clean",),
        verb="{actor} 擦拭吧台，清理酒渍",
        target_match=("bar", "吧台", "酒柜", "调酒台"),
        target_exclude=("barstool", "bar_stool", "高脚凳"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy"),
        object_state_forbidden=("broken", "burn", "clog", "spoil"),
        note="bar_Clean(13022) super=Y auto=Y user=Y tgt=OBJECT Teen+；2026-07-25；2026-07-28 +requires dirty",
    ),
    # ── 2026-07-28 清理 mess（"Make A Mess" 互动产生的脏乱）──
    CustomActionRule(
        rule_id="clean_mess",
        label="🧹 清理脏乱",
        action_type="push",
        target_kind="object",
        hints=("superInteraction_MakeAMess_Cleanup",),
        verb="清理地上的脏乱",
        target_match=("makingamess", "making_a_mess", "mess", "trash_pile"),
        target_exclude=("trashcan", "trash_can", "trashchute", "garbagecan",
                        "washer", "dryer", "hamper", "dishwasher"),
        verified=True,
        auto_trigger=True,
        # 不设 object_state_requires——mess 对象本身就是脏乱，不是"脏的物品"。
        # object_MakingAMess 的 states 字段可能不含 "mess"/"dirty" 关键词，
        # 设了反而把所有 mess 对象都排除了。target_match 已精确锁定。
        object_state_forbidden=("broken", "burn"),
        note="superInteraction_MakeAMess_Cleanup(163254) EA super=Y auto=Y user=Y；2026-07-28 探针确认6实例；2026-07-28 去 object_state_requires——mess对象本身就是脏乱，无独立脏状态；游戏自主体实测已推该交互",
    ),
    # ── 2026-07-28 自动触发扩充：花园/宠物/垃圾桶（全部待实测）──
    CustomActionRule(
        rule_id="water_dry_plants",
        label="🌱 浇干枯植物",
        action_type="push",
        target_kind="object",
        hints=("Gardening_Water_All_Area", "Gardening_Water_Plant"),
        verb="给干枯的植物浇水",
        target_match=("plant", "garden", "植物", "花园", "花盆", "planter",
                      "garden_soil", "gardening", "bush", "tree", "flower"),
        target_exclude=("deco", "fake", "装饰", "假"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dry", "wilted", "withered", "dryout"),
        note="Gardening_Water_All_Area(183148)+Water_Plant 应对植物干旱状态；待实测确认 state 关键词（dry/wilted/withered）",
    ),
    CustomActionRule(
        rule_id="clean_pet_poop",
        label="💩 清理宠物便便",
        action_type="push",
        target_kind="object",
        hints=("petPoop_CleanUp", "CleanUp_PetPoop", "Poop_CleanUp"),
        verb="清理地上的宠物粪便",
        target_match=("poop", "petpoop", "pet_poop", "粪便", "便便"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("poop", "dirty"),
        note="宠物粪便清理 affordance；需猫狗DLC；待实测确认 EA 类名",
    ),
    CustomActionRule(
        rule_id="scoop_litter_box",
        label="🐱 铲猫砂",
        action_type="push",
        target_kind="object",
        hints=("LitterBox_Scoop", "CatLitterBox_Clean", "litterBox_Sift"),
        verb="清理猫砂盆",
        target_match=("litterbox", "litter", "catlitter", "猫砂", "猫厕所"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy", "soiled"),
        note="猫砂盆清理 affordance；需猫狗DLC；待实测确认 EA 类名 + state 关键词",
    ),
    CustomActionRule(
        rule_id="clean_pet_bed",
        label="🐾 清理宠物窝",
        action_type="push",
        target_kind="object",
        hints=("PetBed_Clean", "pet_bed_Clean", "Clean_PetBed"),
        verb="清理脏了的宠物窝",
        target_match=("petbed", "pet_bed", "pet bed", "宠物窝", "宠物床", "狗窝", "猫窝"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("dirty", "filthy"),
        note="宠物窝清理 affordance；待实测确认 EA 类名",
    ),
    CustomActionRule(
        rule_id="empty_trash_outdoor",
        label="🗑 倒户外垃圾桶",
        action_type="push",
        target_kind="object",
        hints=("TrashCan_EmptyOutdoor", "TrashCan_TakeOut", "TakeOutTrash"),
        verb="把满的垃圾桶拿出去倒掉",
        target_match=("trashcan", "trash_can", "garbagecan", "garbage_can",
                      "outdoor_trash", "垃圾桶", "户外垃圾桶"),
        target_exclude=("trashchute", "垃圾槽"),
        verified=False,
        auto_trigger=True,
        object_state_requires=("full", "overflowing"),
        note="倒垃圾桶（非收垃圾堆——那是 collect_trash）；待实测确认 EA 类名 + state 关键词",
    ),
)
